name: CI
on:
  pull_request:
jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t demo-actions-docker .
      - name: Test Image
        run: |
          if [[ ! "$(docker run -e 'INPUT_TEXT=hello' demo-actions-docker)" == "hello" ]]; then
            exit 1
          fi
